// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/bridge/proto/bridge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BridgeEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BridgeEvent_IncomingMessage
	//	*BridgeEvent_OutgoingMessage
	//	*BridgeEvent_ToolCall
	//	*BridgeEvent_ToolResult
	//	*BridgeEvent_Heartbeat
	Payload       isBridgeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BridgeEvent) Reset() {
	*x = BridgeEvent{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BridgeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeEvent) ProtoMessage() {}

func (x *BridgeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BridgeEvent.ProtoReflect.Descriptor instead.
func (*BridgeEvent) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BridgeEvent) GetPayload() isBridgeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BridgeEvent) GetIncomingMessage() *IncomingMessage {
	if x != nil {
		if x, ok := x.Payload.(*BridgeEvent_IncomingMessage); ok {
			return x.IncomingMessage
		}
	}
	return nil
}

func (x *BridgeEvent) GetOutgoingMessage() *OutgoingMessage {
	if x != nil {
		if x, ok := x.Payload.(*BridgeEvent_OutgoingMessage); ok {
			return x.OutgoingMessage
		}
	}
	return nil
}

func (x *BridgeEvent) GetToolCall() *ToolCall {
	if x != nil {
		if x, ok := x.Payload.(*BridgeEvent_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *BridgeEvent) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Payload.(*BridgeEvent_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *BridgeEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*BridgeEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isBridgeEvent_Payload interface {
	isBridgeEvent_Payload()
}

type BridgeEvent_IncomingMessage struct {
	IncomingMessage *IncomingMessage `protobuf:"bytes,2,opt,name=incoming_message,json=incomingMessage,proto3,oneof"`
}

type BridgeEvent_OutgoingMessage struct {
	OutgoingMessage *OutgoingMessage `protobuf:"bytes,3,opt,name=outgoing_message,json=outgoingMessage,proto3,oneof"`
}

type BridgeEvent_ToolCall struct {
	ToolCall *ToolCall `protobuf:"bytes,4,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type BridgeEvent_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type BridgeEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,6,opt,name=heartbeat,proto3,oneof"`
}

func (*BridgeEvent_IncomingMessage) isBridgeEvent_Payload() {}

func (*BridgeEvent_OutgoingMessage) isBridgeEvent_Payload() {}

func (*BridgeEvent_ToolCall) isBridgeEvent_Payload() {}

func (*BridgeEvent_ToolResult) isBridgeEvent_Payload() {}

func (*BridgeEvent_Heartbeat) isBridgeEvent_Payload() {}

type IncomingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // "telegram" or "discord"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{1}
}

func (x *IncomingMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *IncomingMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *IncomingMessage) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type OutgoingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ParseMode     string                 `protobuf:"bytes,4,opt,name=parse_mode,json=parseMode,proto3" json:"parse_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingMessage) Reset() {
	*x = OutgoingMessage{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingMessage) ProtoMessage() {}

func (x *OutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingMessage.ProtoReflect.Descriptor instead.
func (*OutgoingMessage) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{2}
}

func (x *OutgoingMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *OutgoingMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *OutgoingMessage) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *OutgoingMessage) GetParseMode() string {
	if x != nil {
		return x.ParseMode
	}
	return ""
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson string                 `protobuf:"bytes,3,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ResultJson    string                 `protobuf:"bytes,2,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{4}
}

func (x *ToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolResult) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bridge_proto_bridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_bridge_proto_bridge_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_internal_bridge_proto_bridge_proto protoreflect.FileDescriptor

const file_internal_bridge_proto_bridge_proto_rawDesc = "" +
	"\n" +
	"\"internal/bridge/proto/bridge.proto\x12\x06bridge\"\xde\x02\n" +
	"\vBridgeEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\x10incoming_message\x18\x02 \x01(\v2\x17.bridge.IncomingMessageH\x00R\x0fincomingMessage\x12D\n" +
	"\x10outgoing_message\x18\x03 \x01(\v2\x17.bridge.OutgoingMessageH\x00R\x0foutgoingMessage\x12/\n" +
	"\ttool_call\x18\x04 \x01(\v2\x10.bridge.ToolCallH\x00R\btoolCall\x125\n" +
	"\vtool_result\x18\x05 \x01(\v2\x12.bridge.ToolResultH\x00R\n" +
	"toolResult\x121\n" +
	"\theartbeat\x18\x06 \x01(\v2\x11.bridge.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"Z\n" +
	"\x0fIncomingMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"y\n" +
	"\x0fOutgoingMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"parse_mode\x18\x04 \x01(\tR\tparseMode\"g\n" +
	"\bToolCall\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x03 \x01(\tR\rargumentsJson\"a\n" +
	"\n" +
	"ToolResult\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1f\n" +
	"\vresult_json\x18\x02 \x01(\tR\n" +
	"resultJson\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp2H\n" +
	"\rBridgeService\x127\n" +
	"\aConnect\x12\x13.bridge.BridgeEvent\x1a\x13.bridge.BridgeEvent(\x010\x01B7Z5github.com/igoryan-dao/ricochet/internal/bridge/protob\x06proto3"

var (
	file_internal_bridge_proto_bridge_proto_rawDescOnce sync.Once
	file_internal_bridge_proto_bridge_proto_rawDescData []byte
)

func file_internal_bridge_proto_bridge_proto_rawDescGZIP() []byte {
	file_internal_bridge_proto_bridge_proto_rawDescOnce.Do(func() {
		file_internal_bridge_proto_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_bridge_proto_bridge_proto_rawDesc), len(file_internal_bridge_proto_bridge_proto_rawDesc)))
	})
	return file_internal_bridge_proto_bridge_proto_rawDescData
}

var file_internal_bridge_proto_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_bridge_proto_bridge_proto_goTypes = []any{
	(*BridgeEvent)(nil),     // 0: bridge.BridgeEvent
	(*IncomingMessage)(nil), // 1: bridge.IncomingMessage
	(*OutgoingMessage)(nil), // 2: bridge.OutgoingMessage
	(*ToolCall)(nil),        // 3: bridge.ToolCall
	(*ToolResult)(nil),      // 4: bridge.ToolResult
	(*Heartbeat)(nil),       // 5: bridge.Heartbeat
}
var file_internal_bridge_proto_bridge_proto_depIdxs = []int32{
	1, // 0: bridge.BridgeEvent.incoming_message:type_name -> bridge.IncomingMessage
	2, // 1: bridge.BridgeEvent.outgoing_message:type_name -> bridge.OutgoingMessage
	3, // 2: bridge.BridgeEvent.tool_call:type_name -> bridge.ToolCall
	4, // 3: bridge.BridgeEvent.tool_result:type_name -> bridge.ToolResult
	5, // 4: bridge.BridgeEvent.heartbeat:type_name -> bridge.Heartbeat
	0, // 5: bridge.BridgeService.Connect:input_type -> bridge.BridgeEvent
	0, // 6: bridge.BridgeService.Connect:output_type -> bridge.BridgeEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_bridge_proto_bridge_proto_init() }
func file_internal_bridge_proto_bridge_proto_init() {
	if File_internal_bridge_proto_bridge_proto != nil {
		return
	}
	file_internal_bridge_proto_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*BridgeEvent_IncomingMessage)(nil),
		(*BridgeEvent_OutgoingMessage)(nil),
		(*BridgeEvent_ToolCall)(nil),
		(*BridgeEvent_ToolResult)(nil),
		(*BridgeEvent_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_bridge_proto_bridge_proto_rawDesc), len(file_internal_bridge_proto_bridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_bridge_proto_bridge_proto_goTypes,
		DependencyIndexes: file_internal_bridge_proto_bridge_proto_depIdxs,
		MessageInfos:      file_internal_bridge_proto_bridge_proto_msgTypes,
	}.Build()
	File_internal_bridge_proto_bridge_proto = out.File
	file_internal_bridge_proto_bridge_proto_goTypes = nil
	file_internal_bridge_proto_bridge_proto_depIdxs = nil
}
